name: Docker
on:
  push:

jobs:
  build:
    runs-on: nscloud
    steps:
      - uses: actions/checkout@v4
      - name: Build dev container
        if: ${{ github.ref != 'refs/heads/main' }} # dev & feature branches
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm run build
      - name: Build prod container
        if: ${{ github.ref == 'refs/heads/main' }} # dev & feature branches
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm run build
